### ISSUE TITLE
Problem to Install superlu_dist-6.3.1

### ISSUE THREAD

**Issue by angelones** [conda-forge/superlu_dist-feedstock#11]
Issue:
I'm proceeding with the installation of superlu_dist_6.3.1 with CUDA file, the installation stops and does not create the library.
<br/>
Environment (<code>conda list</code>):
ar cr /superlu_dist-6.3.1/makelib/libsuperlu_dist_6.3.1.a \
	dlangs_dist.o dgsequ_dist.o dlaqgs_dist.o dmemory_dist.o dmyblas2_dist.o dsp_blas2_dist.o dsp_blas3_dist.o pdgssvx.o pdgssvx_ABglobal.o dreadhb.o dreadrb.o dreadtriple.o dreadMM.o dbinary_io.o pdgsequ.o pdlaqgs.o dldperm_dist.o pdlangs.o pdutil.o pdsymbfact_distdata.o ddistribute.o pddistribute.o pdgstrf.o dstatic_schedule.o pdgstrf2.o pdGetDiagU.o pdgstrs.o pdgstrs1.o pdgstrs_lsum.o pdgstrs_Bglobal.o pdgsrfs.o pdgsmv.o pdgsrfs_ABXglobal.o pdgsmv_AXglobal.o dreadtriple_noheader.o sp_ienv.o etree.o sp_colorder.o get_perm_c.o colamd.o mmd.o comm.o memory.o util.o superlu_grid.o pxerr_dist.o superlu_timer.o symbfact.o psymbfact.o psymbfact_util.o get_perm_c_parmetis.o mc64ad_dist.o xerr_dist.o smach_dist.o dmach_dist.o superlu_dist_version.o TreeInterface.o
ar: dlangs_dist.o: No such file or directory
make[1]: *** [double] Error 1

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by awvwgk** [comment]
6.3.1 is now packaged with https://github.com/conda-forge/superlu_dist-feedstock/pull/27
