### ISSUE TITLE
Package newer version

### ISSUE THREAD

**Issue by awvwgk** [conda-forge/superlu_dist-feedstock#31]
Newer releases are already available:

- [x] 6.4.0
- [ ] 7.0.0
- [ ] 7.1.0
- [ ] 7.1.1

**Comment by MarDiehl** [comment]
There are some issues when using PETSc with superLU/superLU_dist (https://github.com/conda-forge/petsc-feedstock/issues/125), I would not be surprised if they could be solved by packaging a recent version of superLU_dist

**Comment by awvwgk** [comment]
This issue might be related to the update from superLU_dist from 6.2.0 to 6.3.1 in https://github.com/conda-forge/superlu_dist-feedstock/pull/27, while it is not a major version bump it seems like there might have been a breaking API change. Maybe this is resolved with the newer versions.

I think it might be a good idea to package 6.4.0 as well to see if this persists, before doing the 7er series.
